name: New Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: debian13
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y nodejs wget zip

      - name: Checkout Commit
        uses: actions/checkout@v5

      - name: Install .NET SDK 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: latest
          dotnet-channel: LTS
      
      - name: Build Extension
        run: dotnet publish -c Release
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: "true"

      - name: Zip Compression
        run: |
          mkdir dist
          mv bin/Release/net10.0/publish/browserextension/* dist
          cd dist
          zip -r extension.zip .
          mkdir release && \
          mv extension.zip release/

      - name: Release
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          url: https://codeberg.org
          release-dir: dist/release
          release-notes-file: .assets/release.md
          token: ${{ secrets.FORGEJO_TOKEN }}
